const express=require("express")
const server=express()
const bp=require("body-parser")
//const jsonparser=bp.json()
server.use(bp.json())
const getRoutes=require("./api/getRoutes")
const postRoutes=require("./api/postRoutes")
const contactManager=require("./api/createContact")
server.use("/user",getRoutes)
server.use(postRoutes)
server.use("/",contactManager)
server.listen(3001,()=>console.log("server started"))
