const os=require("os")
console.log("arch",os.arch())
console.log("cpu",os.cpus())
console.log("free memory",os.freemem())
console.log("total memory",os.totalmem())
console.log("type",os.type())
console.log("release",os.release())
